services:
    app:
        container_name: api
        env_file: .env
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        ports:
            - '3000:${PORT}'
        expose:
            - '3000'
        tty: true
        volumes:
            - ./:/app
        links:
            - database
        depends_on:
            database:
                condition: service_healthy
        networks:
            - appnetwork
        restart: always

    database:
        image: 'postgres:17.0-bookworm'
        container_name: db
        env_file: '.env'
        environment:
            POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
        ports:
            - 5432:5432
        expose:
            - '5432'
        volumes:
            - 'db_data:/var/lib/postgresql/data'
        restart: on-failure
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-q',
                    '-d',
                    '${DB_NAME}',
                    '-U',
                    '${DB_USER}',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
        networks:
            - appnetwork

    # postgres migration tool
    goose:
        container_name: goose-runner
        profiles: ['tools']
        env_file: .env
        build:
            context: .
            target: goose
            dockerfile: Dockerfile
        environment:
            GOOSE_DRIVER: postgres
            GOOSE_DBSTRING: postgres://${DB_USER}:${DB_ROOT_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
            GOOSE_MIGRATION_DIR: /migrations
        volumes:
            - ./db/migrations:/migrations
        # https://github.com/pressly/goose?tab=readme-ov-file#usage
        entrypoint: ['goose', '-s', '-timeout', '5m']
        networks:
            - appnetwork
        depends_on:
            database:
                condition: service_healthy
        restart: never

volumes:
    db_data:

networks:
    appnetwork:
