name: 'Build & Push Image - Github'
run-name: 'Build & Push Image - arektacoinstore/web:backend-${{ github.event.inputs.tag }}'

on:
    workflow_dispatch:
        inputs:
            repostiroy:
                type: string
                description: 'Repository Name/Path'
                required: true
            tag:
                type: choice
                description: 'Repository Image Tag'
                default: dev
                required: true
                options:
                    - dev
                    - alpha
                    - beta
                    - prod

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  target: prod
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{github.event.inputs.repository}}-${{ github.event.inputs.tag }}
                  # make repository name static in your app.
