name: 'Release Image'
run-name: 'Release Image - <repo>-${{ github.event.inputs.tag }} - linux/amd64 & linux/arm64'

on:
    workflow_dispatch:
        inputs:
            tag:
                type: choice
                description: 'Repository Image Tag'
                default: dev
                required: true
                options:
                    - dev
                    - beta
                    - prod
            os:
                type: choice
                description: 'Target Operating System'
                default: linux
                required: true
                options:
                    - linux
                    - freebsd
                    - darwin
                    - solaris
                    - openbsd
            arch:
                type: choice
                description: 'Target Architechture'
                default: amd64
                required: true
                options:
                    - amd64
                    - arm64
                    - arm

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_REPOSITORY: '<repo name>'
            PLATFORM_OS: ${{github.event.inputs.os}}
            PLATFORM_ARCHITECHTURE: ${{github.event.inputs.arch}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # dependencies cached by default on root go.sum
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: './go.mod'

            - name: Print Version
              run: go version

            - name: Download & Verify Dependencies
              run: make deps

            - name: Build Release Binary
              run: os=${{env.PLATFORM_OS}} arch=${{env.PLATFORM_ARCHITECHTURE}} make build-release

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  target: release
                  platforms: ${{env.PLATFORM_OS}}/${{env.PLATFORM_ARCHITECHTURE}}
                  push: true
                  tags: ${{env.DOCKERHUB_REPOSITORY}}-${{github.event.inputs.tag}}
